### PR TITLE
Added dashboard for Ben Murrell

### PR DESCRIPTION
**Pull request by misterabdullahAziz**
Link to task:
https://scilifelab.atlassian.net/browse/FREYA-888

### CODE REVIEW

**Comment by Ziip-dev** [comment]
Please provide at least a short description to let me know what is the context of this PR.
As I haven't worked on this, I don't know any details (e.g. clickable link to Jira issue, purpose of the javascript shortcode, etc.)

**Comment by Ziip-dev** [comment]
Also, maybe I missed that during the meetings, any specific reason to put the javascript snippet in a shortcode file?

**Comment by misterabdullahAziz** [comment]
> Please provide at least a short description to let me know what is the context of this PR.
> 
> As I haven't worked on this, I don't know any details (e.g. clickable link to Jira issue, purpose of the javascript shortcode, etc.)

Link for issue, I have added in the description.
There was need to add new dashboard page given by Ben Murrell group (attached in jira issue).

The purpose of the javascript was to get last updated date for the plots. To be consistent with other dashboards I used shortcode as per suggested by senthil.

**Comment by misterabdullahAziz** [comment]
> Also, maybe I missed that during the meetings, any specific reason to put the javascript snippet in a shortcode file?

To be consistent with other dashboards.

**Review by Ziip-dev — APPROVED** [review]
I've refactored the javascript shortcode for higher readability, reusability, and maintainability. If you want to have a final look (I left explaining comments in the commit description).

On my side everything is okay :)

**Pull request merged**
