### PR TITLE
Paul/FREYA-746

### PR DESCRIPTION
**Pull request by Ziip-dev**
- Add last updated date to dashboard cards
- Reorder dashboard cards by most recent update date
- Add filter menu to the dashboard index page
- Display the three most recently updated dashboards on the homepage
- Display the three most recently updated dashboards on the topics pages

### CODE REVIEW

**Comment by Ziip-dev** [comment]
Just to make it clear, I remove the list of dashboards to be displayed in the homepage from the dashboard template.
So initially, all of the dashboards are displayed in the homepage and I added a condition at the end of the function `processDashboardCards` to only keep the three most recent one.

It's not super elegant, but this is the solution that required the least amount of modifications or special conditions... At the end it falls under the top banner short "flicker", so not more noticeable than that.

**Comment by Ziip-dev** [comment]
Same goes for the topic pages as the same script is used

**Comment by Ziip-dev** [comment]
All done @senthil10, if you want to give it one last final check

**Review by senthil10 — COMMENTED** [review]
Great work, looks good to me. If @LianeHughes is also happy, it can be merged

**Review by LianeHughes — COMMENTED** [review]
Looks good. I made an update to the text on GU's dashboard (to make it consistent with KTH and to ensure that users are pointed to relevant data, as is also done elsewhere). I noticed that multi-disease is missing and some dates are incorrect. I assume that's because it requires the EBI file update?

If possible, the Swedish version titles for all, updating, and historic should be changed to 'allt' 'uppdaterad' and 'historisk'

**Comment by Ziip-dev** [comment]
Translation for filter labels added.
@LianeHughes I squashed your commit into the latest one for consistency of the git history once merged :)

**Pull request merged**
