### PR TITLE
Accessibility fixes

### PR DESCRIPTION
**Pull request by senthil10**
Accessibility fix for the following pages

* Homepage
* Contact
* Contribute
* Share data
* Support
* Citation
* Events
* All dashboards

### CODE REVIEW

**Comment by Ziip-dev** [comment]
Looks all good (and looks like a fair amount of work too!) :)
What about the Swedish pages? Do they also need accessibility updates?

**Comment by senthil10** [comment]
> Looks all good (and looks like a fair amount of work too!) :) What about the Swedish pages? Do they also need accessibility updates?

Yes, this is not all, its maybe around 15%. There are still more pages need to be fixed (including the Swedish pages). We will talk about it on Monday sprint planning :)

**Comment by Ziip-dev** [comment]
Okay, so we can still merge this one for now :)

**Comment by senthil10** [comment]
Yes, it can be ^^

**Pull request merged**
